### ISSUE TITLE
Limit characters shown

### ISSUE THREAD

**Issue by visualcookie** [jakemarsh/atom-spotify#21]
Hi,

please add possibility to limit characters shown in status bar. Some tracks may have long Tracknames, Remixnames or Artistnames.

Dean

**Comment by jazzpi** [comment]
You could try adding the following to your stylesheet:

``` less
div.spotify-container {
    max-width: 100px;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
